---
- hosts: ~(b\d+)
  vars:
    dist: "./distros"
    files: "./files"
  remote_user: root
  become: yes
  tasks:
  - name: ping
    ping:
  - name: copy nodes list
    copy: src=files/nodes.ajp_list dest=/etc/httpd/conf.d/nodes.d/nodes.ajp_list
  - name: start httpd
    service: enabled=yes name=httpd state=reloaded
