---
- hosts: ~(s\d)
  vars:
    dist: "./distros"
  remote_user: root
  become: yes
  tasks:
  - name: ping
    ping:
  - name: packages 
    yum: name=sysstat
  - name: packages 
    yum: name=java-1.8.0-openjdk state=latest
  - name: packages 
    yum: name=libselinux-python state=latest
  - name: copy tomcat tgz
    unarchive: copy=yes src={{ dist }}/apache-tomcat-9.0.0.M4.tar.gz dest=/opt
  - name: copy tomcat link
    file: path=/opt/tomcat state=link src=/opt/apache-tomcat-9.0.0.M4
  - name: copy tomcat init
    copy: src=files/tomcat9 dest=/etc/init.d/tomcat9 mode=755
  - name: copy tomcat users
    copy: src=files/tomcat-users.xml dest=/opt/tomcat/conf/tomcat-users.xml
  - name: copy tomcat context
    copy: src=files/context.xml dest=/opt/tomcat/webapps/host-manager/META-INF/context.xml
  - name: copy tomcat context
    copy: src=files/context.xml dest=/opt/tomcat/webapps/manager/META-INF/context.xml
  - name: copy tomcat sample
    copy: src={{ dist }}/sample.war dest=/opt/tomcat/webapps/sample.war
  - name: copy tomcat sampledeploy
    copy: src={{ dist }}/sampledeploy.war dest=/opt/tomcat/webapps/sampledeploy.war
  - name: copy tomcat add service
    command: chkconfig --add tomcat9
  - name: start tomcat
    service: enabled=yes name=tomcat9 state=started pattern=org.apache.catalina.startup.Bootstrap
