#!/bin/bash
#
# tomcat9          Start up the tomcat9 server daemon
#
# chkconfig: 2345 55 25
# description: Tomcat
#

### BEGIN INIT INFO
# Provides: tomcat9
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $syslog
# Should-Start: $syslog
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start up the Tomcat9 server daemon
# Description:       Tomcat
### END INIT INFO

# source function library
. /etc/rc.d/init.d/functions

start()
{
        cd /opt/tomcat/bin
        nohup ./catalina.sh start && success || failure&
        RETVAL=$?
        return $RETVAL
}

stop()
{
        cd /opt/tomcat/bin
        ./catalina.sh stop  start && success || failure
        RETVAL=$?
        return $RETVAL
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
esac
exit $RETVAL

